video:

  prediction:
    input_video_file:
    input_type: 'Camera' # Video or Camera
    frame_per_second: 6
    is_rpi_camera: False
    model_type: CNN #CNN or 3d_CNN
    model_format: IR #IR or h5
    model_file_name: 'MobileNetV2.h5'
    output_type:  # CMD, File or leave it empty to have both
    log_directory_path: ''
    model_input_shape:
      - channels: 3
      - height: 224
      - width: 224
    preprocessing:
      - face_detector: true
      - face_alignment: false
      - spatial_normalization: false
    ir_run:
      # "Required. Path to an .xml file with a trained model."
      model: 'D:\workspace\video-sentimental-analysis\src\Inference\MobileNetV2.xml'
      cpu_extension: # path to a shared library with the kernels implementations
      device: 'CPU' # target device to infer on (CPU, GPU, FPGA, HDDL, MYRIAD or HETERO)