video:

  prediction:
    input_directory: 'D:\Projects\esA\us10\Dataset\ravdess_videos\train\calm\01-02-02-01-01-01-06.mp4'
    input_type: 'Video' # Video or Camera
    frame_per_second: 6
    is_rpi_camera: False
    model_type: CNN #CNN or 3d_CNN
    model_format: IR #IR or h5
    model_directory: 'MobileNetV2.h5'
    output_type:  # CMD, File or leave it empty to have both
    log_file_path: 'D:\workspace\video-sentimental-analysis\src\'
    model_input_shape:
      - channels: 3
      - height: 224
      - width: 224
    preprocessing:
      - face_detector: true
      - face_alignment: false
      - subtraction: false
    ir_run:
      # "Required. Path to an .xml file with a trained model."
      model: 'D:\workspace\video-sentimental-analysis\src\Inference\MobileNetV2.xml'
      cpu_extension: # path to a shared library with the kernels implementations
      device: 'CPU' # target device to infer on (CPU, GPU, FPGA, HDDL, MYRIAD or HETERO)